"""initial schema

Revision ID: 3cda899c9a6b
Revises: 
Create Date: 2026-08-10 22:07:10.610499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cda899c9a6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('target_distance_miles', sa.Float(), nullable=False),
    sa.Column('desired_elevation_gain_ft', sa.Float(), nullable=False),
    sa.Column('route_type', sa.String(length=20), nullable=False),
    sa.Column('algorithm', sa.String(length=20), nullable=False),
    sa.Column('distance_miles', sa.Float(), nullable=False),
    sa.Column('elevation_gain_ft', sa.Float(), nullable=False),
    sa.Column('elevation_loss_ft', sa.Float(), nullable=False),
    sa.Column('estimated_time_minutes', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_points_route_id'), 'route_points', ['route_id'], unique=False)
    op.create_table('route_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_statistics_route_id'), 'route_statistics', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_statistics_route_id'), table_name='route_statistics')
    op.drop_table('route_statistics')
    op.drop_index(op.f('ix_route_points_route_id'), table_name='route_points')
    op.drop_table('route_points')
    op.drop_table('route_records')
    # ### end Alembic commands ###
